config/routes.rb
Rails.application.routes.draw do
  resources :sales
  resources :categories
  resources :products
  resources :sellers
  resources :buyers
  root to: 'page#index'
  get '/newbuyer', to: 'buyers#new'
  get '/newseller', to: 'sellers#new'
  get '/login', to: 'session#new'
  post '/login', to: 'session#create'
  get '/logout', to: 'session#destroy'
  get '/dashboard', to: 'page#admin'
  get '/forbidden', to: 'page#403'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/seller.rb
class Seller < ApplicationRecord
  has_secure_password
  has_many :sales
  before_save {self.email = email.downcase}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 105}, uniqueness: {case_sensitivity: false}, format: {with: VALID_EMAIL_REGEX}
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :birthday, presence: true
end

app/controllers/sellers_controller.rb
class SellersController < ApplicationController
  before_action :set_seller, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:new]
  before_action :require_logged_out, only: [:new]
  before_action :seller_logged_in?
  before_action :require_admin, only: [:index]
  before_action :require_seller, only: [:show]
  before_action :require_same_user, only: [:edit, :update, :delete, :show]

  def require_same_user
    if seller_logged_in?
    @curuser = Seller.find(session[:seller_id])
    end
    if @curuser != Seller.find(params[:id]) && !admin_logged_in?
      redirect_to sellers_path(session[:seller_id])
    end
  end

  # GET /sellers
  # GET /sellers.json
  def index
    @sellers = Seller.all
  end

  # GET /sellers/1
  # GET /sellers/1.json
  def show
    @sale = Sale.all
  end

  # GET /sellers/new
  def new
    @seller = Seller.new
  end

  # GET /sellers/1/edit
  def edit
  end

  # POST /sellers
  # POST /sellers.json
  def create
    @seller = Seller.new(seller_params)

    respond_to do |format|
      if @seller.save
        format.html { redirect_to @seller, notice: 'Seller was successfully created.' }
        format.json { render :show, status: :created, location: @seller }
      else
        format.html { render :new }
        format.json { render json: @seller.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sellers/1
  # PATCH/PUT /sellers/1.json
  def update
    respond_to do |format|
      if @seller.update(seller_params)
        format.html { redirect_to @seller, notice: 'Seller was successfully updated.' }
        format.json { render :show, status: :ok, location: @seller }
      else
        format.html { render :edit }
        format.json { render json: @seller.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sellers/1
  # DELETE /sellers/1.json
  def destroy
    @seller.destroy
    respond_to do |format|
      format.html { redirect_to sellers_url, notice: 'Seller was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_seller
      @seller = Seller.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def seller_params
      params.require(:seller).permit(:first_name,:last_name, :email, :password,:birthday)
    end
end

app/helpers/sellers_helper.rb
module SellersHelper
end

app/views/sellers/_form.html.erb
<div class="register">
  <h1>New Seller</h1>
  <%= form_with(model: seller, local: true) do |form| %>
    <% if seller.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(seller.errors.count, "error") %> prohibited this seller from being saved:</h2>

        <ul>
        <% seller.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
      <p>
      <%= form.label :first_name %>
      <%= form.text_field :first_name %>
      </p>
      <p>
      <%= form.label :last_name %>
      <%= form.text_field :last_name %>
      </p>

      <p>
      <%= form.label :sex %>
      <%= form.select :sex, ['Male', 'Female']%>
      </p>
      <p>
      <%= form.label :birthday %>
      <%= form.date_field :birthday %>
      </p>

      <p>
      <%= form.label :email %>
      <%= form.text_field :email %>
      </p>
      <p>
      <%= form.label :password %>
      <%= form.password_field :password %>
      </p>
      <%= form.submit 'Create Seller', class:'button' =%>
  <% end %>
</div>

app/views/sellers/edit.html.erb
<h1>Editing Seller</h1>

<%= render 'form', seller: @seller %>


<%= link_to 'Back', dashboard_path(session[:admin_id]) %>

app/views/sellers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sellers</h1>
<h1>should only show if admin</h1>
<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sellers.each do |seller| %>
      <tr>
        <td><%= link_to 'Show', seller %></td>
        <td><%= link_to 'Edit', edit_seller_path(seller) %></td>
        <td><%= link_to 'Destroy', seller, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Seller', new_seller_path %>

app/views/sellers/new.html.erb
<%= render 'form', seller: @seller %>

app/views/sellers/show.html.erb
<p id="notice"><%= notice %></p>
<h1>Seller: <%=@seller.email%></h1>

<%= link_to 'Edit my Account', edit_seller_path(@seller) %>
<%= link_to 'Back to Home', seller_path(@seller.id) %>
</br>
<h1>cr for products</h1>
<%= link_to 'Products', products_path%>
</br>
<h1>crud for sales</h1>
<%= link_to 'Sales', sales_path%>
<h1>all my products</h1>
<table>
<tbody>
  <% @sale.each do |sale| %>
    <tr>
      <%if sale.seller_id == session[:seller_id] %>
      <td style='color:red'>Seller: <%= Seller.find(sale.seller_id).email%></td>
      <td>Product: <%= Product.find(sale.product_id).name  %></td>
      <% if sale.buyer_id? %>
      <td>Buyer: <%= Buyer.find(sale.buyer_id).email  %></td>
      <%end%>
      <td><%= link_to 'Edit', edit_sale_path(sale) %></td>
      <td><%= link_to 'Destroy', sale, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <%end%>
    </tr>
  <% end %>
</tbody>
</table>
<h1>available for sale</h1>
<table>
<tbody>
  <% @sale.each do |sale| %>
    <tr>
      <%if sale.seller_id == session[:seller_id] && sale.buyer_id == nil %>
      <td style='color:red'>Seller: <%= Seller.find(sale.seller_id).email%></td>
      <td>Product: <%= Product.find(sale.product_id).name  %></td>
      <% if sale.buyer_id? %>
      <td>Buyer: <%= Buyer.find(sale.buyer_id).email  %></td>
      <%end%>
      <td><%= link_to 'Edit', edit_sale_path(sale) %></td>
      <td><%= link_to 'Destroy', sale, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <%end%>
    </tr>
  <% end %>
</tbody>
</table>
<h1>sold</h1>
<table>
<tbody>
  <% @sale.each do |sale| %>
    <tr>
      <%if sale.seller_id == session[:seller_id] && sale.buyer_id != nil %>
      <td style='color:red'>Seller: <%= Seller.find(sale.seller_id).email%></td>
      <td>Product: <%= Product.find(sale.product_id).name  %></td>
      <% if sale.buyer_id? %>
      <td>Buyer: <%= Buyer.find(sale.buyer_id).email  %></td>
      <%end%>
      <td><%= link_to 'Edit', edit_sale_path(sale) %></td>
      <td><%= link_to 'Destroy', sale, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <%end%>
    </tr>
  <% end %>
</tbody>
</table>