config/routes.rb
Rails.application.routes.draw do
  resources :sales
  resources :categories
  resources :products
  resources :sellers
  resources :buyers
  root to: 'page#index'
  get '/newbuyer', to: 'buyers#new'
  get '/newseller', to: 'sellers#new'
  get '/login', to: 'session#new'
  post '/login', to: 'session#create'
  get '/logout', to: 'session#destroy'
  get '/dashboard', to: 'page#admin'
  get '/forbidden', to: 'page#403'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/page/403.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>error 403: forbidden</h1>
  </body>
</html>

app/views/page/admin.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <center>
    <h1>ADMIN page</h1>

    <h1 style="color:red">list of buyers</h1>
    <% @buyers.each do |buyer| %>
      <tr>
        <h1>email: <%=buyer.email%></h1>
        <td><%= link_to 'Edit', edit_buyer_path(buyer) %></td>
        <td><%= link_to 'Destroy', buyer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      </br>
    <% end %>
    </br>
    <h1 style="color:red">list of sellers</h1>
    <% @sellers.each do |seller| %>
      <tr>
        <h1>email: <%=seller.email%></h1>
        <td><%= link_to 'Edit', edit_seller_path(seller) %></td>
        <td><%= link_to 'Destroy', seller, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      </br>
    <% end %>
    </br>
    <h1>crud for categories</h1>
    <%= link_to 'Categories', categories_path%>
    </br>
    <h1>crud for products</h1>
    <%= link_to 'Products', products_path%>
    </br>
    <h1>rud for sales</h1>
    <%= link_to 'Sales', sales_path%>
    </center>
  </body>
</html>

app/views/page/index.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <center>

    <img src="/pics/title.png" alt="" id="honeydew" >
    <% @sale.each do |sale| %>
    <tr>
      <% if !sale.buyer_id? %>
      <td style='color:red'>Seller: <%= Seller.find(sale.seller_id).email%></td>
      <td>Product: <%= Product.find(sale.product_id).name  %></td>


          <%end%>    </br><%end%>
    </tr>
















    </center>
  </body>
</html>