config/routes.rb
Rails.application.routes.draw do
  resources :sales
  resources :categories
  resources :products
  resources :sellers
  resources :buyers
  root to: 'page#index'
  get '/newbuyer', to: 'buyers#new'
  get '/newseller', to: 'sellers#new'
  get '/login', to: 'session#new'
  post '/login', to: 'session#create'
  get '/logout', to: 'session#destroy'
  get '/dashboard', to: 'page#admin'
  get '/forbidden', to: 'page#403'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/buyer.rb
class Buyer < ApplicationRecord
  has_secure_password
  has_many :sales
  before_save {self.email = email.downcase}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 105}, uniqueness: {case_sensitivity: false}, format: {with: VALID_EMAIL_REGEX}
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :birthday, presence: true
end

app/controllers/buyers_controller.rb
class BuyersController < ApplicationController
  before_action :set_buyer, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:new]
  before_action :require_logged_out, only: [:new]
  before_action :require_buyer, except: [:edit, :new]
  before_action :buyer_or_admin, only: [:edit]
  before_action :require_admin, only: [:index]
  before_action :require_same_user, only: [:edit, :update, :delete, :show]

  def require_same_user
    if buyer_logged_in?
    @curuser = Buyer.find(session[:buyer_id])
    end
    if @curuser != Buyer.find(params[:id]) && !admin_logged_in?
      redirect_to buyer_path(session[:buyer_id])
    end
  end

  # GET /buyers
  # GET /buyers.json
  def index
    @buyers = Buyer.all
  end

  # GET /buyers/1
  # GET /buyers/1.json
  def show
    @sale = Sale.all
  end

  # GET /buyers/new
  def new
    @buyer = Buyer.new
  end

  # GET /buyers/1/edit
  def edit
  end

  def buy
    @sale = Sale.find(params[:id])
    @sale.buyer_id = session[:buyer_id]
    redirect_to buyer_path(session[:buyer_id])
  end

  # POST /buyers
  # POST /buyers.json
  def create
    @buyer = Buyer.new(buyer_params)

    respond_to do |format|
      if @buyer.save
        format.html { redirect_to @buyer, notice: 'Buyer was successfully created.' }
        format.json { render :show, status: :created, location: @buyer }
      else
        format.html { render :new }
        format.json { render json: @buyer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /buyers/1
  # PATCH/PUT /buyers/1.json
  def update
    respond_to do |format|
      if @buyer.update(buyer_params)
        format.html { redirect_to @buyer, notice: 'Buyer was successfully updated.' }
        format.json { render :show, status: :ok, location: @buyer }
      else
        format.html { render :edit }
        format.json { render json: @buyer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buyers/1
  # DELETE /buyers/1.json
  def destroy
    @buyer.destroy
    respond_to do |format|
      format.html { redirect_to buyers_url, notice: 'Buyer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_buyer
      @buyer = Buyer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def buyer_params
      params.require(:buyer).permit(:first_name,:last_name, :email, :password,:birthday)
    end

    def sale_params
      params.require(:sale).permit(:seller_id, :product_id, :price, :buyer_id)
    end
end

app/helpers/buyers_helper.rb
module BuyersHelper
end

app/views/buyers/_form.html.erb
<div class="register">
  <h1>New Buyer</h1>
  <%= form_with(model: buyer, local: true) do |form| %>
    <% if buyer.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(buyer.errors.count, "error") %> prohibited this buyer from being saved:</h2>

        <ul>
        <% buyer.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <p>
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
    </p>
    <p>
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
    </p>
    <p>
    <%= form.label :sex %>
    <%= form.select :sex, ['Male', 'Female']%>
    </p>
    <p>
    <%= form.label :birthday %>
    <%= form.date_field :birthday %>
    </p>
    <p>
    <%= form.label :email %>
    <%= form.text_field :email %>
    </p>
    <p>
    <%= form.label :password %>
    <%= form.password_field :password %>
    </p>
      <%= form.submit 'Create Buyer', class:'button' =%>
  <% end %>
</div>

app/views/buyers/edit.html.erb
<h1>Editing Buyer</h1>

<%= render 'form', buyer: @buyer %>
<% if !admin_logged_in? %>
<%= link_to 'Show', @buyer %> |
<%= link_to 'Back', buyer_url(@buyer.id) %>
<%else%>
<%= link_to 'Back', dashboard_url %>
<%end%>

app/views/buyers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Buyers</h1>
<h1>should only show if admin</h1>
<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @buyers.each do |buyer| %>
      <tr>
        <td><%= link_to 'Show', buyer %></td>
        <td><%= link_to 'Edit', edit_buyer_path(buyer) %></td>
        <td><%= link_to 'Destroy', buyer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Buyer', new_buyer_path %>

app/views/buyers/new.html.erb
<%= render 'form', buyer: @buyer %>

app/views/buyers/show.html.erb
<p id="notice"><%= notice %></p>
<h1>Buyer: <%=@buyer.email%></h1>

<%= link_to 'Edit my Profile', edit_buyer_path(@buyer) %> |
<%= link_to 'Back to Home', buyer_path(@buyer.id) %>
<h1>show available products</h1>

<h1>available products</h1>
<tbody>
  <% @sale.each do |sale| %>
  <% if !sale.buyer_id? %>
      <td style='color:red'>Seller: <%= Seller.find(sale.seller_id).email%></td>
      <td>Product: <%= Product.find(sale.product_id).name  %></td>
            <td>Price: <%= sale.price%></td>
      <%= form_for sale do |s| %>
      <%= s.hidden_field :buyer_id, value: session[:buyer_id]%>
      <%= s.submit "Buy" %>
      <%end%>
      <!-- <td><button type="submit">Buy</button></td> -->
  <%end%>
    </br>
  <%end%>
</tbody>


<h1>show purchases</h1>
<tbody>
  <% @sale.each do |sale| %>
  <% if sale.buyer_id? %>
    <% if sale.buyer_id == session[:buyer_id] %>
      <td style='color:red'>Seller: <%= Seller.find(sale.seller_id).email%></td>
      <td>Product: <%= Product.find(sale.product_id).name  %></td>
      <td>Price: <%= sale.price%></td>
    <%end%>
  <%end%>
    </br>
  <%end%>
</tbody>